services:
  frontend:
    image: "${AWS_ECR_URI}/frontend:latest"
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: "${AWS_ECR_URI}/backend:latest"
    container_name: backend
    ports:
      - "8800:8800"
    networks:
      - app-network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}


volumes:
  mysql-data:

networks:
  app-network: