services:
  frontend:
    image: "${AWS_ECR_URI:-frontend}/frontend:latest"
    ${AWS_ECR_URI:-build: ./frontend}
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: "${AWS_ECR_URI:-backend}/backend:latest"
    ${AWS_ECR_URI:-build: ./backend}
    container_name: backend
    ports:
      - "8800:8800"
    networks:
      - app-network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}


volumes:
  mysql-data:

networks:
  app-network: