services:
  mysql:
    image: mysql:8.4.4
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: crud_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  frontend:
    image: frontend
    build: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_BACKEND_URL=/api

  backend:
    image: backend
    build: ./backend
    container_name: backend
    ports:
      - "8800:8800"
    networks:
      - app-network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - VITE_BACKEND_URL=/api
    depends_on:
      mysql:
        condition: service_healthy


  internal-reverse-proxy:
    image: internal-reverse-proxy
    build: ./internal-reverse-proxy
    container_name: internal-reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network


volumes:
  mysql-data:

networks:
  app-network: