services:
  frontend:
    image: "${AWS_ECR_URI}/frontend:latest"
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network
    environment:
      - VITE_BACKEND_URL=${VITE_BACKEND_URL}

  backend:
    image: "${AWS_ECR_URI}/backend:latest"
    container_name: backend
    ports:
      - "8800:8800"
    networks:
      - app-network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

networks:
  app-network: