services:
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8800:8800"
    networks:
      - app-network
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  mysql:
    image: mysql:8.4.4
    container_name: database
    restart: always
    environment:
      MYSQL_DATABASE: crud_db
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    profiles:
      - local


volumes:
  mysql-data:

networks:
  app-network: