name: Versioning

on:
  push:
    branches:
      - main

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      tag_created: ${{ steps.versioning.outcome }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git describe to work properly

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run versioning script
        id: versioning
        run: bash versioning.sh

  dispatch:
    runs-on: ubuntu-latest
    needs: versioning
    if: needs.versioning.result == 'success'
    steps:
      - name: Send repository dispatch event
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                https://api.github.com/repos/nannanav/infra-repo/dispatches \
                -d '{"event_type": "new-tag", "client_payload": { "tag": "${{ github.ref_name }}" }}'
                